platform :ios, '7.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'BmobSDK', '~> 1.6.6'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
